volumes:
    logs:
        driver: local

services:
    6-12-nutritional-service:
        build: .
        environment:
            docker: "true"
            DB_NAME: "6_12_nutritional_info"
            DB_HOST: "6-12-nutritional-db"
            DB_PORT: "3306"
            DB_USER: "6_12_nutritional_service"
            DB_PASSWORD_FILE: /run/secrets/db_password
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        secrets:
            - db_password
        depends_on:
            6-12-nutritional-db:
                condition: service_healthy
    6-12-nutritional-db:
        image: mysql:9.1.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_DATABASE: "6_12_nutritional_info"
            MYSQL_USER: "6_12_nutritional_service"
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
        healthcheck:
            test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
            timeout: 20s
            retries: 10
        volumes:
            - ./mysql-data:/var/lib/mysql
        secrets:
            - db_password
            - db_root_password

secrets:
    db_password:
        file: db_password.txt
    db_root_password:
        file: db_root_password.txt
